# Generated by Django 5.0.1 on 2024-01-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, max_length=200, null=True)),
                ('institution_code', models.CharField(blank=True, default='UZ', max_length=10, null=True)),
                ('institution_type', models.CharField(blank=True, choices=[('UNIVERSITY', 'UNIVERSITY'), ('COLLEGE', 'COLLEGE'), ('POLYTECHNIC', 'POLYTECHNIC'), ('SCHOOL', 'SCHOOL'), ('INSTITUTE', 'INSTITUTE'), ('ACADEMY', 'ACADEMY'), ('FOUNDATION', 'FOUNDATION')], max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('institution_address', models.TextField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, default='institution_logos/default_logo.jpg', null=True, upload_to='institution_logos')),
                ('active', models.BooleanField(default=True, help_text='active is a boolean field, can either be Tue or False')),
                ('institution_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('founded_year', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
