# Generated by Django 5.0.1 on 2024-01-11 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeNumber', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('job_position', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('RESIGNED', 'RESIGNED'), ('DISMISSED', 'DISMISSED'), ('ON LEAVE', 'ON LEAVE'), ('LEFT ORGANISATION', 'LEFT ORGANISATION')], max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME'), ('CONTRACT', 'CONTRACT')], max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
