# Generated by Django 5.0.1 on 2024-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_profile_picture_applicantpersonaldocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='applicantpersonaldocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('RESUME', 'RESUME'), ('CV', 'CV'), ('IDENTIFICATION', 'IDENTIFICATION'), ('EDUCATIONAL', 'EDUCATIONAL'), ('PROFILE PICTURE', 'PROFILE PICTURE')], max_length=200, null=True),
        ),
    ]
