# Generated by Django 5.0.1 on 2024-03-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0003_remove_applicant_profile_picture_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(help_text='Select the user', on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
                ('skills', models.ManyToManyField(help_text='Select the skill', to='skills.skill')),
            ],
        ),
    ]
