# Generated by Django 5.0.1 on 2024-02-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0003_remove_applicant_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(help_text='Enter the proficiency level', max_length=255)),
                ('applicant', models.ForeignKey(help_text='Select the user', on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
            ],
        ),
    ]
