# Generated by Django 5.0.1 on 2024-02-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant_skills', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantskill',
            name='skill',
            field=models.ManyToManyField(help_text='Select the skill', to='skills.skill'),
        ),
    ]
